[program:rcu]
command=/home/ssl/.pyenv/shims/honcho start
directory=/home/ssl/rcu/
stdout_logfile=/var/log/rcu.log
autostart=true
autorestart=true
startretries=6
user=ssl
stopsignal=SIGINT
environment=DISPLAY=":0",XAUTHORITY="/home/ssl/.Xauthority"
