web:
  host: 0.0.0.0
  port: 8001
  workers: 2
  debug: true
#  public: '/home/fbk/git/footbot2/software/rcu-front'
  public: './public/rcu-front'
  sanic:
    REQUEST_TIMEOUT: 3600
    RESPONSE_TIMEOUT: 3600
    KEEP_ALIVE: True
    KEEP_ALIVE_TIMEOUT: 600

# db:
#   config: '/home/eevee/sanic/data/bm.db'